/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import estructural.Ciclista;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.IServicioCiclista;

/**
 *
 * @author William Duarte
 */
public class GUIActualizarCiclista extends javax.swing.JFrame implements IActualizableCiclista{

    private IServicioCiclista ser;
    /**
     * Creates new form GUIActualizarCiclista
     * @param refSer
     */
    public GUIActualizarCiclista(IServicioCiclista refSer) {
        initComponents();
        ser = refSer; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEquipo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtNumeroAnt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        txtEquipo1 = new javax.swing.JTextField();
        butBuscar1 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualizar");
        setPreferredSize(new java.awt.Dimension(400, 310));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Nombre Nuevo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Equipo Nuevo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));
        getContentPane().add(txtEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 230, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 230, -1));

        txtNumeroAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroAntActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumeroAnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 80, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Número Actual del Ciclista:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 0));
        jLabel7.setText("ACTUALIZAR CICLISTA");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 23, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/aceptar.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setPreferredSize(new java.awt.Dimension(87, 25));
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/aceptarM.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/aceptarS.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/aceptarS.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Equipo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        txtNombre1.setEditable(false);
        getContentPane().add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 130, -1));

        txtEquipo1.setEditable(false);
        getContentPane().add(txtEquipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 110, -1));

        butBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscar.png"))); // NOI18N
        butBuscar1.setBorder(null);
        butBuscar1.setBorderPainted(false);
        butBuscar1.setContentAreaFilled(false);
        butBuscar1.setPreferredSize(new java.awt.Dimension(87, 25));
        butBuscar1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscarS.png"))); // NOI18N
        butBuscar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscarM.png"))); // NOI18N
        butBuscar1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscarM.png"))); // NOI18N
        butBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBuscar1ActionPerformed(evt);
            }
        });
        getContentPane().add(butBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/actual2.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            int numBuq = Integer.parseInt(txtNumeroAnt.getText().trim());     
            actualizar(numBuq);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"Debe introducir un valor de busqueda valido!");
        }
        txtNumeroAnt.setText("");
        txtNombre.setText("");
        txtEquipo.setText("");
        txtNombre1.setText("");
        txtEquipo1.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNumeroAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroAntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroAntActionPerformed

    private void butBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBuscar1ActionPerformed
        try
        {
            int numBuq = Integer.parseInt(txtNumeroAnt.getText().trim());     
            buscar(numBuq);
        }
        catch (Exception e)
        {
            
            JOptionPane.showMessageDialog(null,"Debe introducir un valor de busqueda valido!");
            txtNumeroAnt.setText("");
        }
    }//GEN-LAST:event_butBuscar1ActionPerformed

    public void buscar(int actual)
    {
        try {
            Ciclista p = ser.consultarCiclista(actual);
            
            if(p != null)
            {
                txtNombre1.setText(p.getNombre());
                txtEquipo1.setText(p.getEquipo());
            }
            else
            {
                txtNumeroAnt.setText("");
                txtNombre1.setText("");
                txtEquipo1.setText("");
                JOptionPane.showMessageDialog(null,"El numero actual no se encuentra en la base de datos!");
            }
        } catch (RemoteException ex) {
            Logger.getLogger(GUIActualizarCiclista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void actualizar( int actual)
    {           
        try {
            if(!ser.buscarPorNumero(actual))
            {
                JOptionPane.showMessageDialog(null,"El numero actual no se encuentra en la base de datos!");
            } 
            else
            {
                Ciclista x = ser.buscarPorCiclista(actual);
                String nombre = txtNombre.getText().trim();
                String equipo = txtEquipo.getText().trim();
                
                if(nombre.equals("")&&equipo.equals(""))
                {
                    JOptionPane.showMessageDialog(null,"No se han hecho cambios al ciclista");
                }
                else
                {
                    if(!nombre.equals(""))
                    {
                        x.setNombre(nombre);
                    }
                    
                    if(!equipo.equals(""))
                    {
                        x.setEquipo(equipo);
                    }
                    
                    ser.actualizarCiclista(actual, x);
                    JOptionPane.showMessageDialog(null,"Se ha actualizado!");
                }

            }
        } catch (RemoteException ex) {
            Logger.getLogger(GUIActualizarCiclista.class.getName()).log(Level.SEVERE, null, ex);  
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butBuscar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JTextField txtEquipo;
    private javax.swing.JTextField txtEquipo1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNumeroAnt;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cambio() {
        
    }
}
