/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import estructural.Ciclista;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.IServicioCiclista;

/**
 *
 * @author William Duarte
 */
public class GUIConsultarCiclista extends javax.swing.JFrame implements IActualizableCiclista{

    private IServicioCiclista ser;
    private int numero;
    /**
     * Creates new form GUIConsultarCiclista
     */
    public GUIConsultarCiclista(IServicioCiclista refSer) {
        initComponents();
        ser = refSer;
        numero = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtEquipo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtNumeroBuq = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        butBuscar = new javax.swing.JButton();
        txtNumero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Equipo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        txtEquipo.setEditable(false);
        getContentPane().add(txtEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 240, -1));

        txtNombre.setEditable(false);
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 240, -1));
        getContentPane().add(txtNumeroBuq, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 140, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("DATOS CICLISTA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 105, -1, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Número del ciclista:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 0));
        jLabel7.setText("CONSULTAR CICLISTA");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        butBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscar.png"))); // NOI18N
        butBuscar.setBorder(null);
        butBuscar.setBorderPainted(false);
        butBuscar.setContentAreaFilled(false);
        butBuscar.setPreferredSize(new java.awt.Dimension(87, 25));
        butBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscarS.png"))); // NOI18N
        butBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscarM.png"))); // NOI18N
        butBuscar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscarM.png"))); // NOI18N
        butBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(butBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        txtNumero.setEditable(false);
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 240, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Número:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consul1.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBuscarActionPerformed
        // TODO add your handling code here:
            try 
            {
                numero = Integer.parseInt(txtNumeroBuq.getText().trim()); 
                actualizarCiclista();
            } 
            catch (Exception e) 
            {
                JOptionPane.showMessageDialog(null,"Debe introducir un valor valido.");
            }       
    }//GEN-LAST:event_butBuscarActionPerformed

    public void actualizarCiclista()
    {
        try {
            Ciclista p = ser.consultarCiclista(numero);
            
            if(p != null)
            {
                txtNombre.setText(p.getNombre());
                txtNumero.setText(Integer.toString(p.getNumero()));
                txtEquipo.setText(p.getEquipo());
            }
            else
            {
                txtNombre.setText("");
                txtNumero.setText("");
                txtEquipo.setText("");
                JOptionPane.showMessageDialog(null,"El ciclista no existe!");
            }
        } catch (RemoteException ex) {
            Logger.getLogger(GUIConsultarCiclista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JTextField txtEquipo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtNumeroBuq;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cambio() {
        actualizarCiclista();
    }
}
