/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.IServicioCiclista;

/**
 *
 * @author William Duarte
 */
public class GUIEliminarCiclista extends javax.swing.JFrame {

    private IServicioCiclista ser;
    /**
     * Creates new form GUIEliminarCiclista
     */
    public GUIEliminarCiclista(IServicioCiclista refSer) {
        initComponents();
        ser = refSer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        butEliminar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminar");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("ELIMINAR CICLISTA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 23, -1, -1));
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 220, 20));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Número del ciclista a eliminar:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        butEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        butEliminar.setBorder(null);
        butEliminar.setBorderPainted(false);
        butEliminar.setContentAreaFilled(false);
        butEliminar.setPreferredSize(new java.awt.Dimension(87, 25));
        butEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminarS.png"))); // NOI18N
        butEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminarM.png"))); // NOI18N
        butEliminar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminarM.png"))); // NOI18N
        butEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(butEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/elim1.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEliminarActionPerformed
        // TODO add your handling code here:
        try 
        {
            int numero = Integer.parseInt(txtNumero.getText().trim());
            eliminarCiclista(numero);
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null,"Debe introducir un valor valido!");
        }
        txtNumero.setText("");
    }//GEN-LAST:event_butEliminarActionPerformed

    public void eliminarCiclista(int nId)
    {                
        try {
            boolean ingresar = ser.deleteCiclistaArray(nId);
            
            if(ingresar)
            {
                JOptionPane.showMessageDialog(rootPane,"Se Elimino el ciclista");
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane,"Numero Erroneo!\nNo se encontró el ciclista.");
            }
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(rootPane,"Error: " + ex.getMessage());
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}