/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import estructural.Ciclista;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.IServicioCiclista;

/**
 *
 * @author William Duarte
 */
public class GUIInsertarCiclista extends javax.swing.JFrame {

    private IServicioCiclista ser;
     
    /**
     * Creates new form GUIInsertarCiclista
     */
    public GUIInsertarCiclista(IServicioCiclista refSer) {
        initComponents();
        ser = refSer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEquipo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        butAceptar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Insertar");
        setPreferredSize(new java.awt.Dimension(360, 250));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 240, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 240, -1));

        butAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/aceptar.png"))); // NOI18N
        butAceptar.setBorder(null);
        butAceptar.setBorderPainted(false);
        butAceptar.setContentAreaFilled(false);
        butAceptar.setPreferredSize(new java.awt.Dimension(87, 25));
        butAceptar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/aceptarM.png"))); // NOI18N
        butAceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/aceptarS.png"))); // NOI18N
        butAceptar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/aceptarS.png"))); // NOI18N
        butAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(butAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("INGRESAR NUEVO CICLISTA");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 240, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Número:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Equipo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/insert4.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 360, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAceptarActionPerformed
        // TODO add your handling code here:
        
        try
        {
            String nombre = txtNombre.getText();
            int numero = Integer.parseInt(txtNumero.getText().trim());
            String equipo = txtEquipo.getText();
         
            if(!nombre.equals("") && !equipo.equals("")) 
            {    
                Ciclista nuevo;
                nuevo = new Ciclista(nombre, numero, equipo);
                ingresarCiclista(nuevo);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Debe introducir valores en todos los campos.");
            }
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null,"Debe introducir un valor valido para el campo Número.");
        }    
        
        txtNombre.setText("");
        txtNumero.setText("");
        txtEquipo.setText("");
    }//GEN-LAST:event_butAceptarActionPerformed

    public void ingresarCiclista(Ciclista p)
    {
        try {
            boolean ingresar = ser.addCiclistaArray(p);
            
            if(ingresar)
            {
                JOptionPane.showMessageDialog(null,"Felicidades,\nSe añadio un nuevo Ciclista!");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Lo sentimos,\nEl número ya ha sido registrado!");
            }
        } catch (RemoteException ex) {
            Logger.getLogger(GUIInsertarCiclista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JTextField txtEquipo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
