/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import estructural.Ciclista;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.IServicioCiclista;

/**
 *
 * @author William Duarte
 */
public class GUIListarCiclista extends javax.swing.JFrame implements IActualizableCiclista{

    /**
     * Creates new form GUIListarCiclista
     */
    private IServicioCiclista ser;
    DefaultTableModel modelo;
    
    public GUIListarCiclista(IServicioCiclista refSer) {
        initComponents();
        ser = refSer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        grilla = new javax.swing.JTable();
        butBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listar");
        setPreferredSize(new java.awt.Dimension(350, 470));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LISTADO DE CICLISTAS INSCRITOS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jScrollPane3.setPreferredSize(new java.awt.Dimension(450, 250));

        grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Nombre", "Equipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(grilla);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 220, 300));

        butBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscar.png"))); // NOI18N
        butBuscar.setBorder(null);
        butBuscar.setBorderPainted(false);
        butBuscar.setContentAreaFilled(false);
        butBuscar.setPreferredSize(new java.awt.Dimension(87, 25));
        butBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscarS.png"))); // NOI18N
        butBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscarM.png"))); // NOI18N
        butBuscar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscarM.png"))); // NOI18N
        butBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(butBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/list1.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(350, 250));
        jLabel1.setMinimumSize(new java.awt.Dimension(350, 250));
        jLabel1.setPreferredSize(new java.awt.Dimension(350, 500));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBuscarActionPerformed
       listar();
    }//GEN-LAST:event_butBuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butBuscar;
    private javax.swing.JTable grilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void cambio() {
        listar();
    }
    
    public void listar()
    {
        DefaultTableModel model = (DefaultTableModel)grilla.getModel();
        ArrayList <Ciclista> ciclistas = null;
        
        try {
            ciclistas = ser.darCiclistas();
        } catch (RemoteException ex) {
            Logger.getLogger(GUIListarCiclista.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        model.setRowCount(0);
        for(Ciclista cic: ciclistas){
            model.addRow(new Object[]{cic.getNumero(),cic.getNombre(),cic.getEquipo()});
        }
    }
}
