/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.IServicioCiclista;

/**
 *
 * @author William Duarte
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrincipal
     */
    private IServicioCiclista ser;
    
    public GUIPrincipal(IServicioCiclista refSer) {
        initComponents();
        ser = refSer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butInsertar = new javax.swing.JButton();
        butEliminar = new javax.swing.JButton();
        butListar = new javax.swing.JButton();
        butConsultar = new javax.swing.JButton();
        butActualizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ApliCiclista");
        setMinimumSize(new java.awt.Dimension(455, 290));
        setPreferredSize(new java.awt.Dimension(450, 261));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butInsertar.setBackground(new java.awt.Color(255, 255, 255));
        butInsertar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        butInsertar.setForeground(new java.awt.Color(255, 255, 255));
        butInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/insertar.png"))); // NOI18N
        butInsertar.setBorder(null);
        butInsertar.setBorderPainted(false);
        butInsertar.setContentAreaFilled(false);
        butInsertar.setPreferredSize(new java.awt.Dimension(90, 25));
        butInsertar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/insertarS.png"))); // NOI18N
        butInsertar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/insertarM.png"))); // NOI18N
        butInsertar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/insertarM.png"))); // NOI18N
        butInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(butInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 90, -1));

        butEliminar.setBackground(new java.awt.Color(0, 0, 0));
        butEliminar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        butEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        butEliminar.setBorder(null);
        butEliminar.setBorderPainted(false);
        butEliminar.setContentAreaFilled(false);
        butEliminar.setPreferredSize(new java.awt.Dimension(87, 25));
        butEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminarS.png"))); // NOI18N
        butEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminarM.png"))); // NOI18N
        butEliminar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminarM.png"))); // NOI18N
        butEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(butEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 90, -1));

        butListar.setBackground(new java.awt.Color(0, 0, 0));
        butListar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        butListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/listar.png"))); // NOI18N
        butListar.setBorder(null);
        butListar.setBorderPainted(false);
        butListar.setContentAreaFilled(false);
        butListar.setPreferredSize(new java.awt.Dimension(87, 25));
        butListar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/listarS.png"))); // NOI18N
        butListar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/listarM.png"))); // NOI18N
        butListar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/listarM.png"))); // NOI18N
        butListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butListarActionPerformed(evt);
            }
        });
        getContentPane().add(butListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 80, -1));

        butConsultar.setBackground(new java.awt.Color(0, 0, 0));
        butConsultar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        butConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consultar.png"))); // NOI18N
        butConsultar.setBorder(null);
        butConsultar.setBorderPainted(false);
        butConsultar.setContentAreaFilled(false);
        butConsultar.setPreferredSize(new java.awt.Dimension(87, 25));
        butConsultar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consultarS.png"))); // NOI18N
        butConsultar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consultarM.png"))); // NOI18N
        butConsultar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consultarM.png"))); // NOI18N
        butConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(butConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        butActualizar.setBackground(new java.awt.Color(0, 0, 0));
        butActualizar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        butActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/actualizar.png"))); // NOI18N
        butActualizar.setBorder(null);
        butActualizar.setBorderPainted(false);
        butActualizar.setContentAreaFilled(false);
        butActualizar.setPreferredSize(new java.awt.Dimension(87, 25));
        butActualizar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/actualizarS.png"))); // NOI18N
        butActualizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/actualizarM.png"))); // NOI18N
        butActualizar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/actualizarM.png"))); // NOI18N
        butActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(butActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("Base datos Ciclistas inscritos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, 20));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/principal2.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butInsertarActionPerformed
        try {
            // TODO add your handling code here:
            ViewInsertarCiclista view = new ViewInsertarCiclista(ser);
        } catch (RemoteException ex) {
            Logger.getLogger(GUIPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butInsertarActionPerformed

    private void butEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEliminarActionPerformed
        try {
            // TODO add your handling code here:
            ViewEliminarCiclista view = new ViewEliminarCiclista(ser);
        } catch (RemoteException ex) {
            Logger.getLogger(GUIPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butEliminarActionPerformed

    private void butListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butListarActionPerformed
        try {
            // TODO add your handling code here:
            ViewListarCiclista view = new ViewListarCiclista(ser);
        } catch (RemoteException ex) {
            Logger.getLogger(GUIPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butListarActionPerformed

    private void butConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butConsultarActionPerformed
        try {
            // TODO add your handling code here:
            ViewConsultarCiclista view = new ViewConsultarCiclista(ser);
        } catch (RemoteException ex) {
            Logger.getLogger(GUIPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butConsultarActionPerformed

    private void butActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butActualizarActionPerformed
        try {
            // TODO add your handling code here:
            ViewActualizarCiclista view = new ViewActualizarCiclista(ser);
        } catch (RemoteException ex) {
            Logger.getLogger(GUIPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butActualizarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butActualizar;
    private javax.swing.JButton butConsultar;
    private javax.swing.JButton butEliminar;
    private javax.swing.JButton butInsertar;
    private javax.swing.JButton butListar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelFondo;
    // End of variables declaration//GEN-END:variables
}
